import java.util.*;

public class StringMethods{
    public static void main(String[] args){
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the string value: ");
        String s = sc.nextLine();
        
          
        int[] val = spaces(s);
        System.out.println("The start and the end position of the string after removing leading and trailling spaces are: "+val[0]+" "+ val[1]);
        String substring_val = substring(s,val[0],val[1]);
        System.out.println("The subsring generated by custom  trimming substring method is : " + substring_val); 
        
        String substring_Val1 = s.trim();
        
        boolean ans = compare(substring_val, substring_Val1);
        System.out.println("Both the substrings are same: ? " + ans);
    

        
    }
    
    static boolean compare(String s1, String s2){
        return s1.equals(s2);
    }
    
    static String substring(String s, int st, int e){
        String temp = "";
        for(int i=st;i<=e;i++){
            temp += s.charAt(i);
        }
        
        return temp;
    }
    
    static int[] spaces(String s){
        int st = 0;
        while(st<s.length() && s.charAt(st) == ' '){
            st++;
        }
        
        int e = s.length()-1;
        while(e>=0 && s.charAt(e) == ' '){
            e--;
        }
        
        return new int[] {st,e};
    }
}